title = "Notre-Dame de Paris"
baseURL = ""
languageCode = "en-us"
theme = "ananke"
uglyurls = true
relativeURLs = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = false

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/KrisztianZagonyiOfficial"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  #featured_image = "./images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2